// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQrMMjwvsePtcGUCZtTEpoHqp53WB-R7o',
    appId: '1:897850775671:web:cdf83f4b2663a0feee0e72',
    messagingSenderId: '897850775671',
    projectId: 'greenoville-8f9c1',
    authDomain: 'greenoville-8f9c1.firebaseapp.com',
    storageBucket: 'greenoville-8f9c1.appspot.com',
    measurementId: 'G-ND88VLTR4C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPV2eDgr3AV1mWTHVb7HqU8RNjoy7_FZc',
    appId: '1:897850775671:android:b53d1a5963d11580ee0e72',
    messagingSenderId: '897850775671',
    projectId: 'greenoville-8f9c1',
    storageBucket: 'greenoville-8f9c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC8_66B7rUWUcQR4KzW0wM6gbIZAcAxcY',
    appId: '1:897850775671:ios:c1fb6ea6e7286eb3ee0e72',
    messagingSenderId: '897850775671',
    projectId: 'greenoville-8f9c1',
    storageBucket: 'greenoville-8f9c1.appspot.com',
    iosBundleId: 'com.example.greenovilleApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBC8_66B7rUWUcQR4KzW0wM6gbIZAcAxcY',
    appId: '1:897850775671:ios:dac16b9d687097b4ee0e72',
    messagingSenderId: '897850775671',
    projectId: 'greenoville-8f9c1',
    storageBucket: 'greenoville-8f9c1.appspot.com',
    iosBundleId: 'com.example.greenovilleApp.RunnerTests',
  );
}
